// Generated by gencpp from file number_sensor/IntWithHeader.msg
// DO NOT EDIT!


#ifndef NUMBER_SENSOR_MESSAGE_INTWITHHEADER_H
#define NUMBER_SENSOR_MESSAGE_INTWITHHEADER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace number_sensor
{
template <class ContainerAllocator>
struct IntWithHeader_
{
  typedef IntWithHeader_<ContainerAllocator> Type;

  IntWithHeader_()
    : header()
    , data(0)  {
    }
  IntWithHeader_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , data(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::number_sensor::IntWithHeader_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::number_sensor::IntWithHeader_<ContainerAllocator> const> ConstPtr;

}; // struct IntWithHeader_

typedef ::number_sensor::IntWithHeader_<std::allocator<void> > IntWithHeader;

typedef boost::shared_ptr< ::number_sensor::IntWithHeader > IntWithHeaderPtr;
typedef boost::shared_ptr< ::number_sensor::IntWithHeader const> IntWithHeaderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::number_sensor::IntWithHeader_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::number_sensor::IntWithHeader_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace number_sensor

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'number_sensor': ['/home/catkin_ws/src/number_sensor/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::number_sensor::IntWithHeader_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::number_sensor::IntWithHeader_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::number_sensor::IntWithHeader_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::number_sensor::IntWithHeader_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::number_sensor::IntWithHeader_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::number_sensor::IntWithHeader_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::number_sensor::IntWithHeader_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e7344a45486eefa24d2f337265df37ce";
  }

  static const char* value(const ::number_sensor::IntWithHeader_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe7344a45486eefa2ULL;
  static const uint64_t static_value2 = 0x4d2f337265df37ceULL;
};

template<class ContainerAllocator>
struct DataType< ::number_sensor::IntWithHeader_<ContainerAllocator> >
{
  static const char* value()
  {
    return "number_sensor/IntWithHeader";
  }

  static const char* value(const ::number_sensor::IntWithHeader_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::number_sensor::IntWithHeader_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int32 data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::number_sensor::IntWithHeader_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::number_sensor::IntWithHeader_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IntWithHeader_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::number_sensor::IntWithHeader_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::number_sensor::IntWithHeader_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "data: ";
    Printer<int32_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NUMBER_SENSOR_MESSAGE_INTWITHHEADER_H
